title: Jekyll-SPA
email: pascal@negwer.de
markdown: kramdown
sass:
  sass_dir: _src/sass
  style: compressed
coffee:
  style: compressed
plugins:
  - bootstrap-sass
collections:
  - sections
  - skills